### ISSUE TITLE
The plugin doesn't work

### ISSUE THREAD

**Issue by 8bitFra** [x3mp/EasyKits#1]
I wanted to make a kit including some music discs, but it seems that for some reason the plugin breaks when I try to do this. It seems to work only with one disc, but with the others an exception starts in the console!

I'm on the latest build of PaperSpigot-1.8.8

(with this settings everything works fine, but if i change the disc, from 11 to every other disc the plugin stop working properly)
[Ids reference i used](https://www.digminecraft.com/lists/item_id_list_pc_1_8.php)

Config:
![Immagine 2021-02-24 170725](https://user-images.githubusercontent.com/47214887/109029387-15b7cf00-76c3-11eb-82f0-8aa1641290b7.png)

**Comment by x3mp** [comment]
Hi @8bitFra,

Have you tried putting the itemID in single quotes?
`''`
You can find the reference in the wiki here: [3. Content - ItemID](https://github.com/x3mp/EasyKits/wiki/3.-Content#itemid-)

Hopefully this helps and sorry about the late reply.
