### ISSUE TITLE
Force another user to run the command?

### ISSUE THREAD

**Issue by dchu096** [x3mp/EasyKits#2]
Hey UnrealPixel, is there a way to force another user to run the command?

e.g. `/kit @user game`

Thanks!!

**Comment by x3mp** [comment]
Hi @dchu096,

You can try the essentials "Sudo" command:
`/sudo user command`
Here's a full list of Essentials commands: https://essinfo.xeya.me/commands.html

Hopefully this helps and sorry about the late reply.
